export const list = {
  provider: "KADO",
  name: "KADO",
  timestamp: "2025-01-08T11:07:01.040Z",
  version: {
    major: 1,
    minor: 0,
    patch: 0,
  },
  keywords: [],
  count: 58,
  tokens: [
    {
      chain: "ARB",
      chainId: "42161",
      decimals: 18,
      identifier: "ARB.ETH",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/arb.eth.png",
      ticker: "ETH",
    },
    {
      address: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831",
      chain: "ARB",
      chainId: "42161",
      decimals: 6,
      identifier: "ARB.USDC-0xaf88d065e77c8cC2239327C5EDb3A432268e5831",
      logoURI:
        "https://storage.googleapis.com/token-list-swapkit/images/arb.usdc-0xaf88d065e77c8cc2239327c5edb3a432268e5831.png",
      ticker: "USDC",
    },
    {
      chain: "AVAX",
      chainId: "43114",
      decimals: 18,
      identifier: "AVAX.AVAX",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/avax.avax.png",
      ticker: "AVAX",
    },
    {
      address: "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E",
      chain: "AVAX",
      chainId: "43114",
      decimals: 6,
      identifier: "AVAX.USDC-0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E",
      logoURI:
        "https://storage.googleapis.com/token-list-swapkit/images/avax.usdc-0xb97ef9ef8734c71904d8002f8b6bc66dd9c48a6e.png",
      ticker: "USDC",
    },
    {
      chain: "BASE",
      chainId: "8453",
      decimals: 18,
      identifier: "BASE.ETH",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/base.eth.png",
      ticker: "ETH",
    },
    {
      address: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
      chain: "BASE",
      chainId: "8453",
      decimals: 6,
      identifier: "BASE.USDC-0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
      logoURI:
        "https://storage.googleapis.com/token-list-swapkit/images/base.usdc-0x833589fcd6edb6e08f4c7c32d4f71b54bda02913.png",
      ticker: "USDC",
    },
    {
      chain: "BTC",
      chainId: "bitcoin",
      decimals: 18,
      identifier: "BTC.BTC",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/btc.btc.png",
      ticker: "BTC",
    },
    {
      chain: "ETH",
      chainId: "1",
      decimals: 18,
      identifier: "ETH.ETH",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/eth.eth.png",
      ticker: "ETH",
    },
    {
      address: "0xa5f2211b9b8170f694421f2046281775e8468044",
      chain: "ETH",
      chainId: "1",
      decimals: 18,
      identifier: "ETH.THOR-0xa5f2211b9b8170f694421f2046281775e8468044",
      logoURI:
        "https://storage.googleapis.com/token-list-swapkit/images/eth.thor-0xa5f2211b9b8170f694421f2046281775e8468044.png",
      ticker: "THOR",
    },
    {
      address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
      chain: "ETH",
      chainId: "1",
      decimals: 6,
      identifier: "ETH.USDC-0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
      logoURI:
        "https://storage.googleapis.com/token-list-swapkit/images/eth.usdc-0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48.png",
      ticker: "USDC",
    },
    {
      address: "0xdac17f958d2ee523a2206206994597c13d831ec7",
      chain: "ETH",
      chainId: "1",
      decimals: 6,
      identifier: "ETH.USDT-0xdac17f958d2ee523a2206206994597c13d831ec7",
      logoURI:
        "https://storage.googleapis.com/token-list-swapkit/images/eth.usdt-0xdac17f958d2ee523a2206206994597c13d831ec7.png",
      ticker: "USDT",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.ARS",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.ars.png",
      ticker: "ARS",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.AUD",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.aud.png",
      ticker: "AUD",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.BRL",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.brl.png",
      ticker: "BRL",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.CAD",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.cad.png",
      ticker: "CAD",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.CHF",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.chf.png",
      ticker: "CHF",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.CLP",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.clp.png",
      ticker: "CLP",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.COP",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.cop.png",
      ticker: "COP",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.CRC",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.crc.png",
      ticker: "CRC",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.DKK",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.dkk.png",
      ticker: "DKK",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.EUR",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.eur.png",
      ticker: "EUR",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.GBP",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.gbp.png",
      ticker: "GBP",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.INR",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.inr.png",
      ticker: "INR",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.JPY",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.jpy.png",
      ticker: "JPY",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.KRW",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.krw.png",
      ticker: "KRW",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.MXN",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.mxn.png",
      ticker: "MXN",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.NOK",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.nok.png",
      ticker: "NOK",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.NZD",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.nzd.png",
      ticker: "NZD",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.PEN",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.pen.png",
      ticker: "PEN",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.PHP",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.php.png",
      ticker: "PHP",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.PLN",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.pln.png",
      ticker: "PLN",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.SEK",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.sek.png",
      ticker: "SEK",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.SGD",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.sgd.png",
      ticker: "SGD",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.TRY",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.try.png",
      ticker: "TRY",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.TWD",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.twd.png",
      ticker: "TWD",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.USD",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.usd.png",
      ticker: "USD",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.UYU",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.uyu.png",
      ticker: "UYU",
    },
    {
      chain: "FIAT",
      chainId: "fiat",
      decimals: 2,
      identifier: "FIAT.VND",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/fiat.vnd.png",
      ticker: "VND",
    },
    {
      chain: "GAIA",
      chainId: "cosmoshub-4",
      decimals: 6,
      identifier: "GAIA.ATOM",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/gaia.atom.png",
      ticker: "ATOM",
    },
    {
      address: "ibc/27394fb092d2eccd56123c74f36e4c1f926001ceada9ca97ea622b25f41e5eb2",
      chain: "KUJI",
      chainId: "kaiyo-1",
      decimals: 6,
      identifier: "KUJI.ATOM-ibc/27394fb092d2eccd56123c74f36e4c1f926001ceada9ca97ea622b25f41e5eb2",
      logoURI:
        "https://storage.googleapis.com/token-list-swapkit/images/kuji.atom-ibc/27394fb092d2eccd56123c74f36e4c1f926001ceada9ca97ea622b25f41e5eb2.png",
      ticker: "ATOM",
    },
    {
      address: "ibc/295548A78785A1007F232DE286149A6FF512F180AF5657780FC89C009E2C348F",
      chain: "KUJI",
      chainId: "kaiyo-1",
      decimals: 6,
      identifier:
        "KUJI.axlUSDC-ibc/295548A78785A1007F232DE286149A6FF512F180AF5657780FC89C009E2C348F",
      logoURI:
        "https://storage.googleapis.com/token-list-swapkit/images/kuji.axlusdc-ibc/295548a78785a1007f232de286149a6ff512f180af5657780fc89c009e2c348f.png",
      ticker: "axlUSDC",
    },
    {
      address: "ukuji",
      chain: "KUJI",
      chainId: "kaiyo-1",
      decimals: 6,
      identifier: "KUJI.KUJI-ukuji",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/kuji.kuji-ukuji.png",
      ticker: "KUJI",
    },
    {
      chain: "KUJI",
      chainId: "kaiyo-1",
      decimals: 6,
      identifier: "KUJI.stATOM",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/kuji.statom.png",
      ticker: "stATOM",
    },
    {
      address: "ibc/FE98AAD68F02F03565E9FA39A5E627946699B2B07115889ED812D8BA639576A9",
      chain: "KUJI",
      chainId: "kaiyo-1",
      decimals: 6,
      identifier: "KUJI.USDC-ibc/FE98AAD68F02F03565E9FA39A5E627946699B2B07115889ED812D8BA639576A9",
      logoURI:
        "https://storage.googleapis.com/token-list-swapkit/images/kuji.usdc-ibc/fe98aad68f02f03565e9fa39a5e627946699b2b07115889ed812d8ba639576a9.png",
      ticker: "USDC",
    },
    {
      chain: "LTC",
      chainId: "litecoin",
      decimals: 18,
      identifier: "LTC.LTC",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/ltc.ltc.png",
      ticker: "LTC",
    },
    {
      chain: "OP",
      chainId: "10",
      decimals: 18,
      identifier: "OP.ETH",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/op.eth.png",
      ticker: "ETH",
    },
    {
      address: "0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85",
      chain: "OP",
      chainId: "10",
      decimals: 6,
      identifier: "OP.USDC-0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85",
      logoURI:
        "https://storage.googleapis.com/token-list-swapkit/images/op.usdc-0x0b2c639c533813f4aa9d7837caf62653d097ff85.png",
      ticker: "USDC",
    },
    {
      address: "3B5wuUrMEi5yATD7on46hKfej3pfmd7t1RKgrsN3pump",
      chain: "SOL",
      chainId: "solana",
      decimals: 6,
      identifier: "SOL.BILLY-3B5wuUrMEi5yATD7on46hKfej3pfmd7t1RKgrsN3pump",
      logoURI:
        "https://storage.googleapis.com/token-list-swapkit/images/sol.billy-3b5wuurmei5yatd7on46hkfej3pfmd7t1rkgrsn3pump.png",
      ticker: "BILLY",
    },
    {
      address: "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263",
      chain: "SOL",
      chainId: "solana",
      decimals: 5,
      identifier: "SOL.BONK-DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263",
      logoURI:
        "https://storage.googleapis.com/token-list-swapkit/images/sol.bonk-dezxaz8z7pnrnrjjz3wxborgixca6xjnb7yab1ppb263.png",
      ticker: "BONK",
    },
    {
      address: "9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump",
      chain: "SOL",
      chainId: "solana",
      decimals: 6,
      identifier: "SOL.FARTCOIN-9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump",
      logoURI:
        "https://storage.googleapis.com/token-list-swapkit/images/sol.fartcoin-9bb6nfecjbctnnlfko2fqvqbq8hhm13kcyycdqbgpump.png",
      ticker: "FARTCOIN",
    },
    {
      address: "CzLSujWBLFsSjncfkh59rUFqvafWcY5tzedWJSuypump",
      chain: "SOL",
      chainId: "solana",
      decimals: 6,
      identifier: "SOL.GOAT-CzLSujWBLFsSjncfkh59rUFqvafWcY5tzedWJSuypump",
      logoURI:
        "https://storage.googleapis.com/token-list-swapkit/images/sol.goat-czlsujwblfssjncfkh59rufqvafwcy5tzedwjsuypump.png",
      ticker: "GOAT",
    },
    {
      address: "AZsHEMXd36Bj1EMNXhowJajpUXzrKcK57wW4ZGXVa7yR",
      chain: "SOL",
      chainId: "solana",
      decimals: 6,
      identifier: "SOL.GUAC-AZsHEMXd36Bj1EMNXhowJajpUXzrKcK57wW4ZGXVa7yR",
      logoURI:
        "https://storage.googleapis.com/token-list-swapkit/images/sol.guac-azshemxd36bj1emnxhowjajpuxzrkck57ww4zgxva7yr.png",
      ticker: "GUAC",
    },
    {
      address: "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
      chain: "SOL",
      chainId: "solana",
      decimals: 6,
      identifier: "SOL.JUP-JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
      logoURI:
        "https://storage.googleapis.com/token-list-swapkit/images/sol.jup-jupyiwryjfskupiha7hker8vutaefosybkedznsdvcn.png",
      ticker: "JUP",
    },
    {
      address: "ED5nyyWEzpPPiWimP8vYm7sD7TD3LAt3Q3gRTWHzPJBY",
      chain: "SOL",
      chainId: "solana",
      decimals: 6,
      identifier: "SOL.MOODENG-ED5nyyWEzpPPiWimP8vYm7sD7TD3LAt3Q3gRTWHzPJBY",
      logoURI:
        "https://storage.googleapis.com/token-list-swapkit/images/sol.moodeng-ed5nyywezpppiwimp8vym7sd7td3lat3q3grtwhzpjby.png",
      ticker: "MOODENG",
    },
    {
      chain: "SOL",
      chainId: "solana",
      decimals: 9,
      identifier: "SOL.SOL",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/sol.sol.png",
      ticker: "SOL",
    },
    {
      address: "UPTx1d24aBWuRgwxVnFmX4gNraj3QGFzL3QqBgxtWQG",
      chain: "SOL",
      chainId: "solana",
      decimals: 9,
      identifier: "SOL.UPT-UPTx1d24aBWuRgwxVnFmX4gNraj3QGFzL3QqBgxtWQG",
      logoURI:
        "https://storage.googleapis.com/token-list-swapkit/images/sol.upt-uptx1d24abwurgwxvnfmx4gnraj3qgfzl3qqbgxtwqg.png",
      ticker: "UPT",
    },
    {
      address: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      chain: "SOL",
      chainId: "solana",
      decimals: 6,
      identifier: "SOL.USDC-EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      logoURI:
        "https://storage.googleapis.com/token-list-swapkit/images/sol.usdc-epjfwdd5aufqssqem2qn1xzybapc8g4weggkzwytdt1v.png",
      ticker: "USDC",
    },
    {
      chain: "THOR",
      chainId: "thorchain-1",
      decimals: 8,
      identifier: "THOR.RUNE",
      logoURI: "https://storage.googleapis.com/token-list-swapkit/images/thor.rune.png",
      ticker: "RUNE",
    },
  ],
} as const;
