docs:
- changed-files:
    any-glob-to-any-file:
      - 'internal/playground/**/*'
      - 'docs/**/*'
core:
- changed-files:
    any-glob-to-any-file:
      - 'packages/core/src/**/*'
      - 'packages/helpers/src/**/*'
plugin:
- changed-files:
    any-glob-to-any-file:
      - 'packages/plugins/src/**/*'
toolbox:
- changed-files:
    any-glob-to-any-file:
      - 'packages/toolboxes/src/**/*'

hardware-wallet:
- changed-files:
    any-glob-to-any-file:
      - 'packages/wallets/src/ledger/**/*'
      - 'packages/wallets/src/trezor/**/*'
      - 'packages/wallets/src/keepkey/**/*'

mobile-wallet:
- changed-files:
    any-glob-to-any-file:
      - 'packages/wallets/src/coinbase/**/*'
      - 'packages/wallets/src/exodus/**/*'
      - 'packages/wallets/src/walletconnect/**/*'

browser-extensions:
- changed-files:
    any-glob-to-any-file:
      - 'packages/wallets/src/bitget/**/*'
      - 'packages/wallets/src/talisman/**/*'
      - 'packages/wallets/src/coinbase/**/*'
      - 'packages/wallets/src/ctrl/**/*'
      - 'packages/wallets/src/evm-extensions/**/*'
      - 'packages/wallets/src/keplr/**/*'
      - 'packages/wallets/src/okx/**/*'
      - 'packages/wallets/src/phantom/**/*'
      - 'packages/wallets/src/polkadotjs/**/*'
      - 'packages/wallets/src/radix/**/*'

evm:
- changed-files:
    any-glob-to-any-file:
      - 'packages/toolboxes/src/evm/**/*'
      - 'packages/plugins/src/evm/**/*'

radix:
- changed-files:
    any-glob-to-any-file:
      - 'packages/toolboxes/src/radix/**/*'
      - 'packages/plugins/src/cosmos/**/*'

thorchain:
- changed-files:
    any-glob-to-any-file:
      - 'packages/plugins/src/thorchain/**/*'
      - 'packages/toolboxes/src/cosmos/thorchainUtils/**/*'
      - 'packages/toolboxes/src/cosmos/toolbox/thorchain.*'

chainflip:
- changed-files:
    any-glob-to-any-file:
      - 'packages/plugins/src/chainflip/**/*'

kado:
- changed-files:
    any-glob-to-any-file:
      - 'packages/plugins/src/kado/**/*'

cosmos:
- changed-files:
    any-glob-to-any-file:
      - 'packages/toolboxes/src/cosmos/**/*'

solana:
- changed-files:
    any-glob-to-any-file:
      - 'packages/toolboxes/src/solana/**/*'

substrate:
- changed-files:
    any-glob-to-any-file:
      - 'packages/toolboxes/src/substrate/**/*'

utxo:
- changed-files:
    any-glob-to-any-file:
      - 'packages/toolboxes/src/utxo/**/*'


keystore:
- changed-files:
    any-glob-to-any-file:
      - 'packages/wallets/src/keystore/**/*'
