import { WalletOption } from "@uswap/helpers";
import type { bitgetWallet } from "@uswap/wallet-extensions/bitget";
import type { cosmostationWallet } from "@uswap/wallet-extensions/cosmostation";
import type { ctrlWallet } from "@uswap/wallet-extensions/ctrl";
import type { evmWallet } from "@uswap/wallet-extensions/evm-extensions";
import type { keepkeyBexWallet } from "@uswap/wallet-extensions/keepkey-bex";
import type { keplrWallet } from "@uswap/wallet-extensions/keplr";
import type { okxWallet } from "@uswap/wallet-extensions/okx";
import type { onekeyWallet } from "@uswap/wallet-extensions/onekey";
import type { phantomWallet } from "@uswap/wallet-extensions/phantom";
import type { polkadotWallet } from "@uswap/wallet-extensions/polkadotjs";
import type { talismanWallet } from "@uswap/wallet-extensions/talisman";
import type { tronlinkWallet } from "@uswap/wallet-extensions/tronlink";
import type { vultisigWallet } from "@uswap/wallet-extensions/vultisig";
import type { keepkeyWallet } from "@uswap/wallet-hardware/keepkey";
import type { ledgerWallet } from "@uswap/wallet-hardware/ledger";
import type { trezorWallet } from "@uswap/wallet-hardware/trezor";
import type { coinbaseWallet } from "./coinbase";
import type { keystoreWallet } from "./keystore";
import type { walletSelectorWallet } from "./near-wallet-selector";
import type { passkeysWallet } from "./passkeys";
import type { radixWallet } from "./radix";
import type { walletconnectWallet } from "./walletconnect";
import type { xamanWallet } from "./xaman";

export type SKWallets = {
  [WalletOption.BITGET]: typeof bitgetWallet;
  [WalletOption.BRAVE]: typeof evmWallet;
  [WalletOption.COINBASE_MOBILE]: typeof coinbaseWallet;
  [WalletOption.COINBASE_WEB]: typeof evmWallet;
  [WalletOption.COSMOSTATION]: typeof cosmostationWallet;
  [WalletOption.CTRL]: typeof ctrlWallet;
  [WalletOption.EIP6963]: typeof evmWallet;
  [WalletOption.EXODUS]: typeof passkeysWallet;
  [WalletOption.KEEPKEY]: typeof keepkeyWallet;
  [WalletOption.KEEPKEY_BEX]: typeof keepkeyBexWallet;
  [WalletOption.KEPLR]: typeof keplrWallet;
  [WalletOption.KEYSTORE]: typeof keystoreWallet;
  [WalletOption.LEAP]: typeof keplrWallet;
  [WalletOption.LEDGER]: typeof ledgerWallet;
  [WalletOption.LEDGER_LIVE]: typeof ledgerWallet;
  [WalletOption.METAMASK]: typeof evmWallet;
  [WalletOption.OKX]: typeof okxWallet;
  [WalletOption.OKX_MOBILE]: typeof evmWallet;
  [WalletOption.ONEKEY]: typeof onekeyWallet;
  [WalletOption.PASSKEYS]: typeof passkeysWallet;
  [WalletOption.PHANTOM]: typeof phantomWallet;
  [WalletOption.POLKADOT_JS]: typeof polkadotWallet;
  [WalletOption.RADIX_WALLET]: typeof radixWallet;
  [WalletOption.TALISMAN]: typeof talismanWallet;
  [WalletOption.TREZOR]: typeof trezorWallet;
  [WalletOption.TRONLINK]: typeof tronlinkWallet;
  [WalletOption.TRUSTWALLET_WEB]: typeof evmWallet;
  [WalletOption.VULTISIG]: typeof vultisigWallet;
  [WalletOption.WALLETCONNECT]: typeof walletconnectWallet;
  [WalletOption.WALLET_SELECTOR]: typeof walletSelectorWallet;
  [WalletOption.XAMAN]: typeof xamanWallet;
};

export type SKConnectWallets = SKWallets[keyof SKWallets];

export type SKWalletsSupportedChains = {
  [WalletOption.BITGET]: typeof bitgetWallet.connectBitget.supportedChains;
  [WalletOption.BRAVE]: typeof evmWallet.connectEVMWallet.supportedChains;
  [WalletOption.COINBASE_MOBILE]: typeof coinbaseWallet.connectCoinbaseWallet.supportedChains;
  [WalletOption.COINBASE_WEB]: typeof evmWallet.connectEVMWallet.supportedChains;
  [WalletOption.COSMOSTATION]: typeof cosmostationWallet.connectCosmostation.supportedChains;
  [WalletOption.CTRL]: typeof ctrlWallet.connectCtrl.supportedChains;
  [WalletOption.EIP6963]: typeof evmWallet.connectEVMWallet.supportedChains;
  [WalletOption.EXODUS]: typeof passkeysWallet.connectPasskeys.supportedChains;
  [WalletOption.KEEPKEY]: typeof keepkeyWallet.connectKeepkey.supportedChains;
  [WalletOption.KEEPKEY_BEX]: typeof keepkeyBexWallet.connectKeepkeyBex.supportedChains;
  [WalletOption.KEPLR]: typeof keplrWallet.connectKeplr.supportedChains;
  [WalletOption.KEYSTORE]: typeof keystoreWallet.connectKeystore.supportedChains;
  [WalletOption.LEAP]: typeof keplrWallet.connectKeplr.supportedChains;
  [WalletOption.LEDGER]: typeof ledgerWallet.connectLedger.supportedChains;
  [WalletOption.LEDGER_LIVE]: typeof ledgerWallet.connectLedger.supportedChains;
  [WalletOption.METAMASK]: typeof evmWallet.connectEVMWallet.supportedChains;
  [WalletOption.OKX]: typeof okxWallet.connectOkx.supportedChains;
  [WalletOption.OKX_MOBILE]: typeof evmWallet.connectEVMWallet.supportedChains;
  [WalletOption.ONEKEY]: typeof onekeyWallet.connectOnekeyWallet.supportedChains;
  [WalletOption.PASSKEYS]: typeof passkeysWallet.connectPasskeys.supportedChains;
  [WalletOption.PHANTOM]: typeof phantomWallet.connectPhantom.supportedChains;
  [WalletOption.POLKADOT_JS]: typeof polkadotWallet.connectPolkadotJs.supportedChains;
  [WalletOption.RADIX_WALLET]: typeof radixWallet.connectRadixWallet.supportedChains;
  [WalletOption.TALISMAN]: typeof talismanWallet.connectTalisman.supportedChains;
  [WalletOption.TREZOR]: typeof trezorWallet.connectTrezor.supportedChains;
  [WalletOption.TRONLINK]: typeof tronlinkWallet.connectTronLink.supportedChains;
  [WalletOption.TRUSTWALLET_WEB]: typeof evmWallet.connectEVMWallet.supportedChains;
  [WalletOption.VULTISIG]: typeof vultisigWallet.connectVultisig.supportedChains;
  [WalletOption.WALLETCONNECT]: typeof walletconnectWallet.connectWalletconnect.supportedChains;
  [WalletOption.WALLET_SELECTOR]: typeof walletSelectorWallet.connectWalletSelector.supportedChains;
  [WalletOption.XAMAN]: typeof xamanWallet.connectXaman.supportedChains;
};
