export const list = {
  chainId: "harbor-1",
  count: 4,
  keywords: [],
  name: "HARBOR",
  provider: "HARBOR",
  timestamp: "2025-11-26T00:04:29.470Z",
  tokens: [
    {
      chain: "BTC",
      chainId: "bitcoin",
      decimals: 8,
      identifier: "BTC.BTC",
      logoURI: "https://storage.googleapis.com/token-list-swapkit-dev/images/btc.btc.png",
      shortCode: "b",
      ticker: "BTC",
    },
    {
      chain: "ETH",
      chainId: "1",
      decimals: 18,
      identifier: "ETH.ETH",
      logoURI: "https://storage.googleapis.com/token-list-swapkit-dev/images/eth.eth.png",
      shortCode: "e",
      ticker: "ETH",
    },
    {
      chain: "ETH",
      chainId: "1",
      decimals: 18,
      identifier: "ETH.ETH",
      logoURI: "https://storage.googleapis.com/token-list-swapkit-dev/images/eth.eth.png",
      shortCode: "e",
      ticker: "ETH",
    },
    {
      address: "0xdAC17F958D2ee523a2206206994597C13D831ec7",
      chain: "ETH",
      chainId: "1",
      decimals: 18,
      identifier: "ETH.USDT-0xdAC17F958D2ee523a2206206994597C13D831ec7",
      logoURI:
        "https://storage.googleapis.com/token-list-swapkit-dev/images/eth.usdt-0xdac17f958d2ee523a2206206994597c13d831ec7.png",
      shortCode: "eth.usdt",
      ticker: "USDT",
    },
  ],
  version: { major: 1, minor: 0, patch: 0 },
} as const;
