export enum Chain {
  Arbitrum = "ARB",
  Aurora = "AURORA",
  Avalanche = "AVAX",
  Base = "BASE",
  Berachain = "BERA",
  BinanceSmartChain = "BSC",
  Cardano = "ADA",
  Botanix = "BOTANIX",
  Core = "CORE",
  Corn = "CORN",
  Cronos = "CRO",
  Bitcoin = "BTC",
  BitcoinCash = "BCH",
  Cosmos = "GAIA",
  Dash = "DASH",
  Dogecoin = "DOGE",
  Ethereum = "ETH",
  Gnosis = "GNO",
  Harbor = "HARBOR",
  Hyperevm = "HYPEREVM",
  Kujira = "KUJI",
  Sonic = "SONIC",
  Unichain = "UNI",
  XLayer = "XLAYER",
  Litecoin = "LTC",
  Maya = "MAYA",
  Near = "NEAR",
  Noble = "NOBLE",
  Optimism = "OP",
  Polkadot = "DOT",
  Chainflip = "FLIP",
  Polygon = "POL",
  Radix = "XRD",
  Ripple = "XRP",
  THORChain = "THOR",
  Solana = "SOL",
  Sui = "SUI",
  Ton = "TON",
  Tron = "TRON",
  Zcash = "ZEC",
}

export enum StagenetChain {
  Harbor = "MAYA_HARBOR",
  THORChain = "THOR_STAGENET",
  Maya = "MAYA_STAGENET",
}

/**
 * ChainId enum - chain identifiers for different networks
 *
 * Note: Full-name properties (e.g., Arbitrum, Avalanche) will be discontinued in future versions.
 * Please use the short-handle properties (e.g., ARB, AVAX) instead.
 * The network configuration will be migrated to a more streamlined approach with one object per chain.
 */
export enum ChainId {
  Arbitrum = "42161",
  Aurora = "1313161554",
  Avalanche = "43114",
  Base = "8453",
  Berachain = "80094",
  BinanceSmartChain = "56",
  Bitcoin = "bitcoin",
  BitcoinCash = "bitcoincash",
  Botanix = "3637",
  Cardano = "cardano",
  Chainflip = "chainflip",
  Core = "1116",
  Corn = "21000000",
  Cosmos = "cosmoshub-4",
  Cronos = "25",
  Dash = "dash",
  Dogecoin = "dogecoin",
  Ethereum = "1",
  Gnosis = "100",
  Harbor = "harbor-1",
  HarborStagenet = "harbor-stagenet-1",
  Hyperevm = "2868",
  Kujira = "kaiyo-1",
  Litecoin = "litecoin",
  Maya = "mayachain-mainnet-v1",
  MayaStagenet = "mayachain-stagenet-v1",
  Near = "near",
  Noble = "noble-1",
  Optimism = "10",
  Polkadot = "polkadot",
  Polygon = "137",
  Radix = "radix-mainnet",
  Ripple = "ripple",
  Solana = "solana",
  Sonic = "146",
  Sui = "sui",
  THORChain = "thorchain-1",
  THORChainStagenet = "thorchain-stagenet-v2",
  Ton = "ton",
  Tron = "728126428",
  Unichain = "130",
  XLayer = "196",
  Zcash = "zcash",
}
