name: Run build, test & publish
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  TEST_API_KEY: ${{ secrets.TEST_API_KEY }}

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - develop
      - v4
  push:
    branches:
      - develop
      - beta
      - nightly

jobs:
  build-lint-test:
    if: contains(github.event.pull_request.title, ':tada:') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Repo
        uses: ./tools/github/setup-repo

      - run: bun build:ci
      - run: bun lint
      - run: bun type-check:ci

      - name: Test
        if: contains(github.ref_name, 'nightly') == false
        run: bun test:ci

  publish:
    if: contains(github.ref_name, 'develop') || contains(github.ref_name, 'nightly') || contains(github.ref_name, 'beta')
    needs: [build-lint-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Repo
        uses: ./tools/github/setup-repo

      - name: Replace versions
        run: bun run ./scripts/replace-versions.ts

      - name: Copy npmrc config
        run: cp .npmrc.prod .npmrc

      - name: Set job params
        shell: bash
        id: deployment-params
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          echo "publishName=${{ github.ref_name == 'develop' && 'Release' || github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Exit pre changeset
        if: contains(github.ref_name, 'nightly')
        continue-on-error: true
        run: bun changeset pre exit

      - name: Change nightly changeset
        if: contains(github.ref_name, 'nightly')
        run: bun changeset version --snapshot nightly

      - name: Change beta changeset
        if: contains(github.ref_name, 'beta')
        continue-on-error: true
        run: bun changeset pre enter beta


      - name: Create Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1.4.10
        if: contains(github.ref_name, 'develop')
        with:
          title: ":tada: Publish ${{ steps.deployment-params.outputs.publishName }}"
          version: bun version-bump
          publish: bun publish-packages
          setupGitUser: false
          createGithubReleases: false

      - name: Publish Beta to npm
        uses: changesets/action@v1.4.10
        if: contains(github.ref_name, 'beta')
        with:
          title: ":tada: Publish Beta"
          version: bun version-bump
          publish: bun publish-packages --no-git-tag
          setupGitUser: false
          createGithubReleases: false

      - name: Publish Nightly to npm
        uses: changesets/action@v1.4.10
        if: contains(github.ref_name, 'nightly')
        with:
          title: ":tada: Publish Nightly"
          version: bun version-bump
          publish: bun publish-packages --tag nightly --no-git-tag
          setupGitUser: false
          createGithubReleases: false

  build-docs:
    runs-on: ubuntu-latest
    needs: [build-lint-test]
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Repo
        uses: ./tools/github/setup-repo

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install, build, and upload your site
        uses: withastro/action@v4
        with:
          path: ./docs
          package-manager: bun

  deploy:
    needs: [build-docs]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
